[general]
# Ruta absoluta dentro del contenedor (debe estar en el volumen montado)
dbpath = /db/comments.db
# Tu blog en GitHub Pages
host = https://ilsonmangas.github.io/
# El nombre de tu sitio para el correo/interfaz
name = mi-blog

[server]
# Escuchar en todas las IPs del contenedor en el puerto 8080
listen = http://0.0.0.0:8080/
# Importante para que Railway sepa que está vivo
reload = true

[guard]
enabled = true
ratelimit = 2
direct-reply = 3
reply-to-self = false
require-author = false

[markup]
options = "autolink"
